// Licensed under the MIT License. See LICENSE in the project root for license information.

using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace OpenAI.Responses
{
    [Preserve]
    public sealed class LocalShellCall : IResponseItem
    {
        [Preserve]
        [JsonConstructor]
        internal LocalShellCall(
            [JsonProperty("id")] string id,
            [JsonProperty("type")] ResponseItemType type,
            [JsonProperty("object")] string @object,
            [JsonProperty("status")] ResponseStatus status,
            [JsonProperty("action")] LocalShellAction action,
            [JsonProperty("call_id")] string callId)
        {
            Id = id;
            Type = type;
            Object = @object;
            Status = status;
            Action = action;
            CallId = callId;
        }

        [Preserve]
        public LocalShellCall(LocalShellAction action)
        {
            Type = ResponseItemType.LocalShellCall;
            Action = action;
        }

        /// <inheritdoc />
        [Preserve]
        [JsonProperty("id", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Id { get; }

        /// <inheritdoc />
        [Preserve]
        [JsonProperty("type", DefaultValueHandling = DefaultValueHandling.Include)]
        public ResponseItemType Type { get; }

        /// <inheritdoc />
        [Preserve]
        [JsonProperty("object", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Object { get; }

        /// <inheritdoc />
        [Preserve]
        [JsonProperty("status", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public ResponseStatus Status { get; }

        /// <summary>
        /// Execute a shell command on the server.
        /// </summary>
        [Preserve]
        [JsonProperty("action")]
        public LocalShellAction Action { get; }

        /// <summary>
        /// The unique ID of the local shell tool call generated by the model.
        /// </summary>
        [Preserve]
        [JsonProperty("call_id")]
        public string CallId { get; }
    }
}
